DESCRIPTION = [
  "Renting out my garage for your parking needs. Don't mind my tools!",
  "I have a lovely spot on the side of my house. It is super long and narrow for my types of vehicles.",
  "I just finished decorating my spot with concrete bricks and new AC. Ready to be used!",
  "My garage is very spacious for many car sizes.",
  "Don't mind the 'Do Not Park' sign! I own this curb side spot and will kindly lend it to you. :) ",
  "I got rid of my cars last month and don't mind lending out my garage to you folks. Please book!",
  "My driveway is perfect for nights out or when you are on vacation.",
  "My new house's driveway is too big for me. Help me fill up space!",
  "Check out my spot and book now!",
  "My sleek new garage is ready to parked in! I reply fast to your booking requests! Guarenteed!",
  "Come visit and take a look! I have relatively nice neighborhood for your parking needs.",
  "This property has too big of a driveway. I only have one car, so I have plenty of room.",
  "If you need parking, I am your guy! Check it out for yourself!",
  "My property has a huge driveway entrance for many cars. Book now and I'll reply ASAP!",
  "Just finished remodeling my parking space for your parking needs. Check it out!",
  "I have new house with brand new slurry driveway. I am open to any types of bookings.",
  "My price is very negotiable. Please book now and I'll contant you.",
  "This spot is perfect for your needs. There is an express bus stop around the corner that goes straight to the city",
  "Ready to be parked and booked. Quiet neighborhood with friendly neighbors.",
  "Hello, I am renting my spot to you and would like to make your life easier. Please book now and I will reply ASAP.",
  "My indoor garage is ready to be parked at! I also give complimentary car washes.",
  "I don't normally use my tool shed, so it would be perfect for anyone to use for long periods of parking times.",
  "My garage would be perfect for many motorcycles.",
  "Hello, I am renting my spot to you and would like to make your life easier. Please book now and I will reply ASAP.",
  "Come visit and take a look! I have relatively nice neighborhood for your parking needs.",
  "Check out my spot and book now!",
  "Come visit and take a look! I have relatively nice neighborhood for your parking needs.",
  "I just finished decorating my spot with concrete bricks and new AC. Ready to be used!",
  "Please make sure to move your car for street cleaning!",
  "My property has a huge driveway entrance for many cars. Book now and I'll reply ASAP!",
  "Just finished remodeling my parking space for your parking needs. Check it out!",
  "Come visit and take a look! I have relatively nice neighborhood for your parking needs.",
  "Check out my spot and book now!",
  "Come visit and take a look! I have relatively nice neighborhood for your parking needs.",
  "I just finished decorating my spot with concrete bricks and new AC. Ready to be used!",
  "Please make sure to move your car for street cleaning!",
  "My property has a huge driveway entrance for many cars. Book now and I'll reply ASAP!",
  "Just finished remodeling my parking space for your parking needs. Check it out!",
  "Just finished remodeling my parking space for your parking needs. Check it out!",
  "I have new house with brand new slurry driveway. I am open to any types of bookings.",
  "My price is very negotiable. Please book now and I'll contant you.",
  "This spot is perfect for your needs. There is an express bus stop around the corner that goes straight to the city",
  "Ready to be parked and booked. Quiet neighborhood with friendly neighbors.",
  "My new property has a cool parking dock that can fit at least 8 cars underground. Perfect for long visits!",
  "Hello, I am renting my spot to you and would like to make your life easier. Please book now and I will reply ASAP.",
  "My indoor garage is ready to be parked at! I also give complimentary car washes.",
  "I don't normally use my tool shed, so it would be perfect for anyone to use for long periods of parking times.",
  "My garage would be perfect for many motorcycles. I designed it myself!",
  "Just finished remodeling my parking space for your parking needs. Check it out!",
  "This parking spot was built by me! You park above my car hidden underground"
]
