GOOD_REVIEWS = [
  "This spot was a really nice place to park! Highly recommend it!",
  "Quiet area and friendly neighborhood, felt very comfortable keeping my car here",
  "My ferrari was carefully watched over by the host :)",
  "The host was kind enough to move my car to street cleaning. Super nice",
  "This driveway is perfect! I keep my car here every week",
  "While I was out on vacation, the host assured my car would be kept in mint condition",
  "Great spot!",
  "Fantastic spot!",
  "It's very nice",
  "The owner was really friendly and showed me around the neighborhood too",
  "This spot saved me from getting parking ticket",
  "Enjoyed my night out and returned to my car in perfect condition",
  "The host was really helpful in making my night out great",
  "This driveway was perfect for my irregular size car",
  "My friends and I were able to fit 3 motorcycles!",
  "My RV usually doesn't have a place to stay. Thank god for this parking spot",
  "This driveway allowed me to enjoy a night out in town",
  "The neighborhood felt very safe for me to park",
  "Saved myself over $300 a month parking here instead!",
  "Lifesaver!",
  "This was great but not the best",
  "Probably the best parking spot I parked at. ever.",
  "I can't imagine parking anywhere else after seeing this spot!",
  "I am extremely careful about where I park my expensive luxury car. This spot met my picky needs",
  "This spot saved me a couple hundred a month",
  "LOVED IT!",
  "This host and driveway were awesome",
  "You wont regret it!",
  "Parking here has been very easy",
  "Saved a ton a time parking here instead of looking for parking in the busy city",
  "Bigger spot than advertised!",
  "This spot made life much easier for me",
  "I save 30 min every morning parking here and it's close to an express bus stop",
  "In all of town, this spot was very helpful to park at",
  "The host was great!",
  "Don't know what I do without this parking spot",
  "This was an awesome spot!",
  "Wonderful!",
  "Good enough for my needs",
  "Highly recommended",
  "Parking is hard to find in this neighborhood. This driveway was very useful",
  "Easy to park at and host was cool",
  "Can't imagine how it would be like to find parking in this neighborhood without this driveway",
  "This driveway met my needs",
  "AWESOME!",
  "COOL!",
  "Parking is a mess around here. This host can sell a lot more than he lists for right now",
  "Parking is very limited in this area. Highly recommended",
  "I don't know what I would do without this spot",
  "Why hasn't anyone showed me this sonner!",
  "Great!",
  "I'm definitly coming back",
  "I saved $20 a week by parking here!",
  "Comparably cheaper than other parking garages in the area",
  "Cool looking driveway",
  "I like the curb apeal and garage",
  "Left and came back with no scratches on my 1985 Mustang!",
  "So much cheaper than my apartment complex garage",
  "Parking here is better than the other spots in the area",
  "Where would I be without this spot??? Seriously the best",
  "This driveway was exceptional",
  "Exquisite!",
  "Parking is this area is tough. Book fast!",
  "The host was super easy to work with",
  "The spot was relatively easy to find",
  "Suprising the host isn't charging more. Book while it's cheap!",
  "I can't imagine parking anywhere else",
  "So easy to find and park at",
  "My truck was able to fit in and out easily in this spot",
  "I usually don't trust these sort of things but this spot changed my whole outlook",
  "Parking made easy",
  "Parking was super easy",
  "Like all the reviews. It was awesome!",
  "Great! Highly recommend it",
  "Can I book for a year instead? :)",
  "Cool looking spot and comes with car fresheners",
  "The host was super nice and offered to wash my car!",
  "The neighborhood parking sucks. Thank god for this spot",
  "Parking was cool",
  "Met my relatively high standards for most parking spots",
  "I'm very picky when it comes to parking. So trust me when I say that this parking spot was great",
  "Sooo cool!",
  "Chepaer than anywhere else!",
  "definitely coming back again!",
  "YES. FINALLY SOMEONE ON MY BLOCK POSTED A SPOT! Its so hard to park in my area",
  "Why isn't this parking spot featured?!",
  "Nice!",
  "good enough for my needs",
  "You won't regret parking here!",
  "This spot was super nice",
  "For some reason, the weather here is much better than other parts",
  "This parking spot rocks!",
  "Parking is unbearable around here. Book fast!",
  "The host is really nice and offered me cookies",
  "It took my weeks to finally find a decent spot for my BMW. This spot was perfect.",
  "PERFECT!",
  "Don't know what I would do without this spot",
  "Parking everywhere else is such a hassle. Just book already",
  "I loved my experience here",
  "Felt confident in leaving my car here",
  "Can parking be any easier?",
  "I spend a lot time in this area, so parking here would save you a ton of tiem",
  "Enjoy your night out and come back to your car scratch free!",
  "Host is very reliable. I even left my keys with him",
  "I'll definitely come back because of the host",
  "I wish I owned this spot",
  "He could make a living if he charged more! Get it while it's cheap everyone",
  "Don't hesitate. This spot is always booked.",
  "The host picked me up and dropped me off to my event!",
  "Space is limited in this part of the city, so i would book early",
  "The host was extremely nice",
  "Great!",
  "Fantastic spot with a nice view",
  "Nearby restaurants make this spot even nicer to park at",
  "I wish I lived here!",
  "Can I park my car here forever?",
  "Parking is very simple here",
  "Best parking spot ever!",
  "Why can't everyone in this neighborhood rent out their driveway???",
  "This parking spot saves me so much money",
  "My coworkers also started parking here because the host was so nice.",
  "Loyal customer to a fantastic host!",
  "It is super nice in this area",
  "Where else would you have parked? Just park here!",
  "Park here now!",
  "Very cool spot, I like the lawn too",
  "If only this spot was available on the weekends...",
  "Don't park anywhere else but here. Seriously.",
  "relatively more quiet and safe here than other parts of the district",
  "This host was remarkable!",
  "Best parking spot in all of town!",
  "I am from out of town and this parking spot definitely was lifesaver for my rental car",
  "I leave my car here every week!",
  "This host was great to meet and work with",
  "My car was super safe here in this area.",
  "This spot was great!",
  "I have been parking here for the past week and it was been awesome so far",
  "No complaints!",
  "Parking around here sucks. This spot is definitely great to have.",
  "The host reponds very quickly!",
  "Don't park anywhere else but here. The neighbors are also friendly.",
  "I'd park here every week if I could, but it's always booked!",
  "I wish he had another spot for me and my wife",
  "Close to the bus stop I take into the city!",
  "Much easier to park at than other places. Don't waste your time anywhere else",
  "Park here now!",
  "Don't think. Just book!",
  "My car can't be anymore secure here.",
  "I dont park anywhere else but here!",
  "Private driveway is always better to park at",
  "Just park here already",
  "Book now!",
  "Where else would you park?",
  "I've seen other parking spots and this is amazing!",
  "This parking spot standed out the most to me",
  "Much cheaper than other parking garages around the area.",
  "I wish I had spot like this!",
  "Dont park anywhere else. I got my window broken into, but thank god this host has guard dog",
  "Safe and friendly neighborhood",
  "10 minute walk away from my work!",
  "Can't imagine parking anywhere else in the city!",
  "It was super nice to park here. Great spot!",
  "Highly recommed it. Book it",
  "This has been the greatest parking spot ever!",
  "The best driveway in the whole world!",
  "If you parked here, you won't regret it",
  "Fantastic spot! I wish it was available more often",
  "Why can't this spot be mine! :(",
  "This host is so lucky to have a parking spot so close to fun areas.",
  "I undertand why this parking spot is always booked. It was amazing.",
  "Best parking experience I've ever had",
  "This parking spot is always booked. Book early!",
  "The host was easy to talk to and made me feel confident to park here",
  "I park here every month and save $100!",
  "The host is super friendly.",
  "My car has never been safer than any other parking spot!",
  "Best parking spot listed on this website!",
  "It was so great to meet the host and park at this property",
  "This driveway was amazing to park at!",
  "Parking around here is extremely difficult. So lucky to have found about this spot.",
  "If you hate looking for parking, go here!",
  "Quiet street and safe neighborhood. I'd park here again.",
  "This parking spot made my day so much easier!",
  "Nowhere else in town can you park here for this cheap.",
  "No issues. Highly recommend it.",
  "It was awesome parking here!",
  "Book now and you won't regret doing so!",
  "I parked here almost every day so far. I love it!",
  "Loved it!",
  "Amazingly convenient spot to parking at.",
  "A very convenient spot if you're late to work.",
  "This price is negotiable! The host is easy to talk to.",
  "This spot was the best parking spot I've ever left my car at.",
  "Parking was way easier now that I found this spot.",
  "I can't imagine parking anwhere else now!",
  "Book this spot! Trust me!",
  "An amazing spot.",
  "Best driveway ever!",
  "Great host and fantastic spot in town"
]
