TITLES = [
  "Indoor private garage",
  "Long private driveway",
  "Driveway w/ new asphalt",
  "Private garage for rent",
  "Curb side parking",
  "Newly spacious garage parking",
  "Driveway in popular area",
  "Spacious driveway",
  "Super huge driveway",
  "Private indoor garage",
  "New concrete driveway",
  "Private Brick driveway",
  "Private two car garage and driveway",
  "Huge parking space driveway",
  "Newly finished driveway",
  "Private Driveway",
  "Two car driveway",
  "Private residential neighborhood driveway",
  "New driveway for you!",
  "Parking in Downtown",
  "Indoor garage",
  "Tool shed parking",
  "Small and cozy garage",
  "Long and narrow brick driveway",
  "Private Driveway",
  "Parking in Chinatown",
  "Newly painted and remodeled driveway",
  "Newly finished driveway",
  "Private Driveway",
  "Two car driveway",
  "Private residential neighborhood driveway",
  "New driveway for you!",
  "Parking in busy Downtown",
  "Check me out! New Driveway",
  "Sloped parking",
  "Parking driveway for rent",
  "Driveway for rent",
  "Driveway w/ new asphalt",
  "Private garage for rent",
  "Curb side parking",
  "Newly spacious garage parking",
  "Driveway in popular area",
  "Spacious driveway",
  "Modern elevated parking",
  "Private two car garage and driveway",
  "Huge parking space driveway",
  "Newly finished driveway",
  "Private Driveway",
  "Hidden parking spot",
  "Underground parking"
]
